function [BW,maskedImage] = segmentImage(RGB,MASK)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB,MASK) segments image RGB using
%  auto-generated code from the Image Segmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 26-Mar-2026
%----------------------------------------------------



% Create empty mask
BW = false(size(RGB,1),size(RGB,2));

% Load Mask
BW = MASK;

% Erode mask with default
radius = 8;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Erode mask with default
radius = 1;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

