function properties = analyzeRegions(BW)

properties = regionprops(BW, ...
    'BoundingBox', ...
    'Area', ...
    'Circularity', ...
    'Eccentricity', ...
    'Extent', ...
    'Solidity', ...
    'Perimeter');

end