function drawTracks(frameRGB, tracks, vehicleCount, colors)

    % Dodaj bounding boxy z ID
    ann = frameRGB;

    for t = 1:length(tracks)

        ann = insertObjectAnnotation( ...
            ann, ...
            'rectangle', ...
            tracks(t).bbox, ...
            sprintf('ID %d', tracks(t).id), ...
            'TextBoxOpacity', 0.9, ...
            'FontSize', 18);

    end

    % Wyświetl obraz
    imshow(ann);
    hold on;

    % Rysowanie trajektorii
    for t = 1:length(tracks)

        p = tracks(t).path;

        if size(p,1) > 1

            c = colors( ...
                mod(tracks(t).id - 1, size(colors,1)) + 1, :);

            % linia trajektorii
            plot( ...
                p(:,1), ...
                p(:,2), ...
                '-', ...
                'Color', c, ...
                'LineWidth', 2);

            % aktualna pozycja
            plot( ...
                p(end,1), ...
                p(end,2), ...
                'o', ...
                'Color', c, ...
                'MarkerFaceColor', c, ...
                'MarkerSize', 6);

        end

    end

    % Licznik pojazdów
    text( ...
        20, ...
        20, ...
        sprintf('Vehicles: %d', vehicleCount), ...
        'Color', 'yellow', ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', 'black');

    hold off;

end